version: "3"
services:
  mongodb:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks: 
      - roofus

  backend:
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/roofus
    build:
      context: ./backend
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks: 
      - roofus

  frontend:
    environment:
      - CONFIG='{"API_BASE_URL":"http://backend:3000/api"}'

    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:3000"
    networks: 
      - roofus

networks:
  roofus:
    driver: bridge